name: zero_two_one_trade_assignment
description: A modular monolith foundation for a Flutter trading application.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  auto_route: ^11.1.0
  account_funds:
    path: packages/features/account_funds
  dashboard:
    path: packages/features/dashboard
  fund:
    path: packages/features/fund
  orders:
    path: packages/features/orders
  orderbook:
    path: packages/features/orderbook
  portfolio:
    path: packages/features/portfolio
  profile:
    path: packages/features/profile
  watchlist:
    path: packages/features/watchlist
  search:
    path: packages/features/search
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  core_data:
    path: packages/foundation/core_data
  core_ui:
    path: packages/foundation/core_ui
  navigation_contract:
    path: packages/navigation/navigation_contract
  injectable: ^2.5.2

dev_dependencies:
  auto_route_generator: ^10.6.0
  build_runner: ^2.15.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
