name: fund
description: Fund feature presentation package.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.1

dependencies:
  core_ui:
    path: ../../foundation/core_ui
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
