name: core_ui
description: Shared lightweight UI foundations and components.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/fonts/Poppins-Medium.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-SemiBold.ttf
